"""add authentication fields to users

Revision ID: 92fb3a3c6bf3
Revises: 145aee3483ab
Create Date: 2026-09-17 18:54:18.159364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92fb3a3c6bf3'
down_revision: Union[str, Sequence[str], None] = '145aee3483ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # La columna es NOT NULL. Como la tabla puede contener usuarios previos a la
    # autenticación, se añade con un server_default temporal (un hash placeholder
    # que no coincide con ninguna contraseña real) para poblar las filas existentes.
    # Luego se retira el default para que el esquema coincida con el modelo ORM.
    placeholder = "$2b$12$invalidinvalidinvalidinvalidinvalidinvalidinvalidinvalidinv"
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'hashed_password',
                sa.String(length=255),
                nullable=False,
                server_default=placeholder,
            )
        )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('hashed_password', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('hashed_password')

    # ### end Alembic commands ###
